---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[chef-repo::default]
    attributes:
  - name: ca_test
    run_list:
      - recipe[chef-repo::chef_ca]
    attributes:
  - name: nzb_server
    run_list:
      - recipe[setup]
      - recipe[jml-defaults]
      - recipe[nzbget]
      - recipe[sonarr]
