---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[jml-ubuntu-defaults]
    attributes:
      dev_mode: true
  - name: without_admin_user
    run_list:
      - recipe[jml-ubuntu-defaults]
    attributes:
      dev_mode: true
      jml-ubuntu-defaults:
        admin_user: false
