#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: lwrp_x509
    run_list:
      - recipe[test::lwrp_x509]
  - name: lwrp_rsa_key
    run_list:
      - recipe[test::lwrp_rsa_key]
  - name: lwrp_signing_req
    run_list:
      - recipe[test::lwrp_signing_req]
